---
services:
  serverless:
    image: amaysim/serverless:3.39.0
    env_file: .env
    volumes:
      - ~/.aws:/root/.aws:Z
      - ~/.ssh:/root/.ssh:Z
      - .:/opt/app:Z
      - ~/.yarn-cache:/usr/local/share/.cache/yarn/v1:Z
  pep8:
    image: eeacms/pep8
    volumes:
      - .:/code:Z
    network_mode: "none"
    working_dir: /code
  virtualenv:
    build: .
    env_file: .env
    working_dir: /usr/src/app
    entrypoint: []
    volumes:
      - ./:/usr/src/app:Z
  lambda:
    image: public.ecr.aws/lambda/python:3.11
    env_file: .env
    volumes:
      - ./run:/var/task:Z
  lambda-test:
    image: public.ecr.aws/lambda/python:3.11
    env_file: .env
    expose:
      - 8080
    command:
      - slack_cloudfront_bot.unit_test
    volumes:
      - ./run:/var/task:Z
